TUGAS1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import percobaan.urls as percobaan
from percobaan.views import index as index_percobaan
import app_1.urls as app_1
import app_2.urls as app_2
import app_3.urls as app_3

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index_percobaan , name='index'),
    url(r'^percobaan/', include(percobaan,namespace='index')),
    url(r'^app-1/', include(app_1 , namespace='app-1')),
    url(r'^app-2/', include(app_2 , namespace='app-2')),
    url(r'^friends/', include(app_3,namespace='app-3')),
]

app_1/urls.py
from django.conf.urls import url
from .views import index, add_status
from . import views

urlpatterns = [
	url(r'^$', index, name='index'),
	
	url(r'^add_status', add_status, name='add_status'),
	
	 
]

app_2/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

app_3/urls.py
from django.conf.urls import url
from .views import index, add_friend
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_friend', add_friend, name='add_friend'),
    ]

percobaan/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

app_1/models.py
from django.db import models

class Status(models.Model):
	description = models.TextField()
	created_date = models.DateTimeField(auto_now_add=True)

app_2/models.py
from django.db import models

# Create your models here.
class Data(models.Model):
	name = models.CharField(max_length=25)
	birthday = models.CharField(max_length=20)
	gender = models.CharField(max_length=6)
	expertise = models.TextField()
	description = models.TextField()
	email = models.EmailField()
	imageurl = models.TextField()

app_3/models.py
from django.db import models

class Friend(models.Model):
    name = models.CharField(max_length=27)
    url = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name + self.url

percobaan/models.py
from django.db import models

# Create your models here.

app_1/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
   
    
    description_attrs = {
        'type': 'text',
        'cols': 35,
        'rows': 8,
        'class': 'status-form-textarea',
        'placeholder':'Apa yang anda pikirkan?...'
    }

    
    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))
	

app_3/forms.py
from django import forms

class Friend_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    name_attrs = {
        'type': 'text',
        'class': 'name-form',
        'placeholder': 'Masukan nama...',
    }
    url_attrs = {
        'type': 'text',
        'class': 'url-form',
        'pattern': '^(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$',
        'placeholder': 'Masukan url... (ex: http://debug-blaster.herokuapp.com)',
    }

    name = forms.CharField(label='Nama', max_length=27, required=True, widget=forms.TextInput(attrs=name_attrs))
    url = forms.CharField(widget=forms.TextInput(attrs=url_attrs), max_length=27, required=True)

app_1/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

from app_3.models import Friend

from .forms import Status_Form
from .models import Status

# Create your views here.

response = {}
def index(request):
	
    response['author'] = "Rafif Iqbal Shaputra" #TODO Implement yourname
    status= Status.objects.all()
    count_status=Status.objects.all().count()
    friend= Friend.objects.all().count()
    response['friend']=friend
    response['status'] = status[::-1]
    response['count_status']=count_status
	
    html = 'app_1/app_1.html'
    response['status_form'] = Status_Form
	
    return render(request, html, response)

def add_status(request):
    form = Status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['description'] = request.POST['description']
        status = Status(description=response['description'])
        status.save()
        return HttpResponseRedirect('/app-1/')
    else:
        return HttpResponseRedirect('/app-1/')
		

app_2/views.py
from django.shortcuts import render
from .models import Data

# Create your views here.
response = {}

def __init__():
	response['name'] = "Rafif Iqbal Shaputra"
	response['birthday'] = "1 January 1998"
	response['gender'] = "Male"
	response['expertise'] = [{'exp' : 'Marketing'},{'exp' : 'Collector'},{'exp' : 'Public Speaking'}]
	response['description'] = "Aesthetique Sekali. Selalu mencoba menjadi yang terbaik apapun yang terjadi.\
								Meski badai dan topan menghadang, ku kan terus berlari, berlari.. lari.. ri.. rii.. riiii...."
	response['email'] = "rafif.doang@gmail.com"
	response['imageurl'] = "https://www.w3schools.com/howto/img_avatar.png"

	data = Data(name=response['name'], birthday=response['birthday'], gender=response['gender'], expertise=response['expertise'],\
			description=response['description'], email=response['email'], imageurl=response['imageurl'])
	data.save()

__init__()
def index(request):
	html = 'app_2/app_2.html'
	return render(request, html, response)

app_3/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Friend_Form
from .models import Friend

response = {'author' : "Kelompok 3A"}

def index(request):
    response['content'] = 'sesuatu'
    html = 'app_3/app_3.html'
    friend = Friend.objects.all()
    friend = reversed(friend)
    response['friend'] = friend
    response['friend_form'] = Friend_Form
    print(response['friend_form'])
    return render(request, html, response)

def add_friend(request):
    form = Friend_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['url'] = request.POST['url']
        friend = Friend(name=response['name'], url=response['url'])        
        friend.save()        
        return HttpResponseRedirect('/friends/')
    else:        
        print("tidak valid")
        return HttpResponseRedirect('/friends/')

percobaan/views.py
from django.shortcuts import render
from datetime import datetime, date
# Enter your name here
mhs_name = 'Nathaniel Nicholas' # TODO Implement this
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(1998,10,19) #TODO Implement this, format (Year, Month, Date)
# Create your views here.
def index(request):
    response = {'name': mhs_name, 'age': calculate_age(birth_date.year)}
    return render(request, 'index.html', response)

def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0

app_1/templates/app_1/app_1.html
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<style>

	
	

	
	
	
	.left-content{
	
				
		width:25%;
		height:700px;
		float:left;
		margin-left:10px;
		
	}

	.right-content{
		
		width:100%;
		
		float:left;
		
	}
	
	.right2-content{
		float:left;
		height:700px;
		width:22%;
		margin-right:20px;
	
	}
	
	.img{
	float:left;
	padding-top:10px;
	padding-right:5px;
	padding-left:15px;
	width:68px;
	height:68px;
	}
	
	.img-flex{
	float:left; 
	padding-top:10px;
	padding-right:5px;
	padding-left:15px;
	width:45;
	height:45;
	}
	
	.post-button{
	
		margin-left:100px;
		margin-top:10px;
		background:#2C97DF;
		color:white;
		border-top:0;
		border-left:0;
		border-right:0;
		border-bottom:5px solid #2A80B9;
		padding:10px 20px;
		text-decoration:none;
		font-family:sans-serif;
		font-size:11pt;
		text-decoration:bold;
	}
	
	.flex{
		
		
		padding-left:7px;
		padding-right:7px;
		padding-top:18px;
		padding-bottom:5px;
	}
	
	.flex-item{
	
		background-color:#F5F5F5;
		padding-left:15px;
		padding-right:15px;
		padding-bottom:20px;
		
		word-wrap:break-word;
		border :3px solid white;
		border-radius:6px;
	}
	
	.flex-item-tem{
		
		word-wrap:break-word;
		border-bottom:4px solid black;
		border-radius: 10px;
		margin-bottom:20px;
		padding-bottom:20px;
		padding-left:30px;
		padding-right:10px;
		border-right:4px solid black;
		background-color:white;
		border-left: 4px solid black;
	}
	.tulisan-tulis{
		margin-left:155px;
		font-family:sans-serif;
		font-size:24pt;
		text-decoration:bold;
	}
	.img-prof{
	padding-top:25px;
	padding-left:50px;
		width:165px;
		height:165px;
		
	}
	
	.tulisan2{
		margin-left:35px;
		font-family:sans-serif;
		font-size:16pt;
		
	}
	
	.tulisan3{
		margin-left:80px;
		font-family:sans-serif;
		font-size:12pt;
		
	}
	
	.nama{
			margin-left:10px;
			padding-bottom:5px;
			font-size:16pt;
			position: absolute ;
			top: -9999px ;
			left: -9999px ;
	}
	
	
	
	

	#input-list{
	margin-left:70px;
		margin-top:50px;
		background: linear-gradient(to bottom right, #606062, #393939);
		color:white;
		border: 4px solid rgb(135, 206, 235, 0.6);
		border-radius: 10px ;
		width:450px;
		
	}
	
	#tulisan{
		margin-left:30px;
		color:white;
		background-color:gray;
		border: 4px solid rgb(135, 206, 235, 0.6);
		border-radius: 5px;
		width:550px;
		
		
	}
	
	#my-list{
		margin-left:75px;
		width:450px;
		padding-right:5px;
		padding-left:5px;
			}
	
	#form{
		padding-top:10px;
		padding-left:10px;
		padding-bottom:10px;
		margin-left:85px;
		margin-top:20px;
	}
	
	
	
	#list-profile{
	margin-top:10px;
	margin-left:40px;
		background-color:white;
		width:300px;
		height:350px;
	}
	
	#list-friend{
	margin-left:40px;
		background-color:white;
		width:300px;
		height:500px;
	}
	
	#list-friend2{
	margin-top:10px;
		margin-right:35px;
		background-color:white;
		width:300px;
		height:600px;
	}
	
	
	#my-list{
	
	}
	
	.icon_post{
		width:30px;
		height:30px;
		padding-right:20px;
		float:left;
	}
	
	
	
	@media only screen and (max-width:768px) {
		.left-content {
			
		
			position: absolute ;
			top: -9999px ;
			left: -9999px ;
		 
		}
	
		.right-content{
			width :auto;
			margin-left:0px;
			float:none;
			
	}
	
		#input-list{
		
			width:320px;
			margin-left:12px;
			margin-right:0px;
		}
		

		.img{
		margin-left:75px;
		width:150px;
		height:150px;
			
			padding-bottom:5px;
		}
		
		
		
		.nama{
			position: relative ;
			top: 18px ;
			left: 5px ;
		}
		
		.post-button{
			margin-left:110px;
			margin-bottom:10px;
		}
		
		.tulisan-tulis{
		margin-left:90px;
		font-family:sans-serif;
		font-size:16pt;
		text-decoration:bold;
	}
	
	.tulisan4{
	margin-top:180px;
	font-size:16pt;
	font-family:sans-serif;
	margin-left:70px;
	color:gray;
	}
	
	.tulisan5{
	
	font-size:13pt;
	font-family:sans-serif;
	margin-left:130px;
	color:gray;
	}
		
		#tulisan{
			margin-left:8px;
			margin-right:0px;
			width:320px;
		}
		
			#form{
		width:310px;
		padding-top:5px;
		padding-left:10 px;
		padding-right:10px;
		padding-bottom:0px;
		margin-left:10px;
		margin-top:0px;
		}
	
	#my-list{
		margin-right:0px;
		margin-left:8px;
		width:320px;
		margin-bottom:10px;
	}
	
	#belakang{
	width:100%;
	
	background-color:#FFEFD5;
	
	padding-bottom:20px;
	padding-top:2px;
	}
	
	#belakang_2{
	background-color:#B0E0E6	;
		padding-bottom:20px;
	padding-top:5px;
	
	}
	
	
	
	}
	
	
	
	
	
	</style>


</head>

{% block content %}

<div class="right-content">

<div id="belakang">
<img src="http://www.mediafire.com/convkey/db67/bmkz78dok9w1ww6zg.jpg" class="img"  />
<p class="tulisan4">
		<b> Rafif Iqbal Shaputra</b>
</p>
<p class="tulisan5">
		<b><img src="https://cdn3.iconfinder.com/data/icons/line-icons-medium-version/64/comment-512.png" class="icon_post"\>{{count_status}}<br><br>
		<img src="https://cdn4.iconfinder.com/data/icons/eldorado-user/40/friends-512.png" class="icon_post"/>  {{friend}} <b>
</p>
<section name="input-list" id="input-list">
    <div class="container_1">
		<div style=”text-align:justify;width:75%; background-color:#ff9999; border:1px solid #000099; padding:8px;”>
		
		<p class="nama" > <b> Whats Happening?</p> </b></div>
        <form id="form" method="POST" action="{% url 'app-1:add_status' %}">
            {% csrf_token %}
            {{ status_form }}
            <input id="submit" type="submit" class="post-button" value="Post">
            
        </form>
		
    </div>
</section>
</div>

<section id="belakang_2">
<section name="tulisan" id="tulisan">
	<p class="tulisan-tulis">
	<b>See All Status</b>
	</p>
</section>

<section name="my-list" id="my-list">
    <div class="container_2">
	
        <div class="flex">
		
            {% if status %}
				
                {% for data in status %}
				<div class="flex-item">
				<p style="font-size:10pt ;font-family:Courier;">
				 <img src="http://www.mediafire.com/convkey/db67/bmkz78dok9w1ww6zg.jpg" class="img-flex"  />
				<br>Rafif Iqbal Shaputra<br>{{data.created_date}} <hr>
				</p>
				<p style="font-size:10pt; font-family:Courier; text-align:justify;">
				 {{data.description}}
				 </p>
				 </div>
				 <br>
				
				
                {% endfor %}
				
				
			
            {% else %}
		
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada data status.
            </div>
            {% endif %}
        </div>
	
    </div>
</section>
</div>
</div>

{% endblock %}

app_1/templates/app_1/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="LAB 5">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/app_1.css' %}" />

    <title>
        {% block title %} Lab 5 By {{author}} {% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "app_1/partials/header.html" %}
    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "app_1/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>
</body>
</html>

app_1/templates/app_1/partials/footer.html
<!-- templates/lab_5/partials/footer.html -->
<!-- TODO, CREATE THIS FILE AND ADD copyright symbol -->
<p>Made with Love by {{author}}</p>

app_1/templates/app_1/partials/header.html
<!-- templates/app_1/partials/header.html -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <!-- LINK MENUJU table, dan link menuju home#form -->
        <li><a href="{% url 'app-1:index' %}#input-list">Input Todo</a></li>
        <li><a href="{% url 'app-1:index' %}#my-list">My List</a> </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app_2/templates/app_2/app_2.html
{% extends "app_2/layout/base.html" %}
{% block content %}
<h1><a href="#" id="href_bio">Profile</a></h1>
<hr/>
<section name="bio">
	<center>
		<div class="container">
			<center>
				<img class="img-circle" src={{imageurl}} width="250" height="250">
			</center>
			<h3 align="center"> {{name}} </h3>
			<table align="center" style="text-align: justify">
				<tr>
					<td> Birthday </td>
					<td> {{birthday}} </td>
				</tr>
				<tr>
					<td> Gender </td>
					<td> {{gender}} </td>
				</tr>
				<tr>
					<td> Expertise </td>
					<td>
						<ul class="allTags">
							{% for exp in expertise %}
								<li>
									<a class="tag">{{exp.exp}}</a>
								</li>
							{% endfor %}
						</ul>
					</td>
				</tr>
				<tr>
					<td> Description </td>
					<td> {{description}} </td>
				</tr>
				<tr>
					<td> Email </td>
					<td> {{email}} </td>
				</tr>
		</div>
	</center>
</section>

{% endblock %}

app_2/templates/app_2/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>
		{% block title %} Profile {% endblock %}
    </title>
</style>
<style>
	h1, h3, td {
		font-family: "Calibri";
	}
	h1 a {
		color: #000000;
		text-decoration: none;
	}
	hr {
		border: 1px transparent;
	}
	td {
		vertical-align: top;
		max-width: 560px;
		word-wrap: break-word;
		padding-left: 20px;
		padding-right: 20px;
		padding-bottom: 8px;
	}
	.allTags {
		list-style: none;
		margin: 0;
		overflow: hidden;
		padding: 0;
	}
	.tags li {
		float: left;
	}
	.tag {
		background: #eeeeee;
		border-radius: 10px;
		display: inline-block;
		height: 26px;
		line-height: 26px;
		padding: 0 20px 0 23px;
		position: relative;
		margin: 0 10px 5px 0;
		text-decoration: none;
		-webkit-transition: color 0.2s;
	}
	.tag:hover {
		background-color: #3a5fff;
		color: white;
	}
	.tag:hover::after {
		border-left-color: #3a5fff; 
	}
	.img-circle {
		border-radius : 50%;
	}
	.container {
		border-radius: 5%;
		padding-top: 30px;
		padding-bottom: 30px;
		height: auto;
		width: 800px;
		background: #fff;
	}
</style>
<body style="background-color: #eeeeee">
	{% block content %}
		<!-- content goes here -->
	{% endblock %}
</body>
</html>

app_3/templates/app_3/app_3.html
{% extends "app_3/layout/base.html" %}

{% block content %}
    <div class= "contain">
      <form class= "friend-form" method="POST" action="{% url 'app-3:add_friend' %}">
        <h2>Add Friend</h2>
        {% csrf_token %}
        {{ friend_form }}
        <button  class="friend-button">Add friend</button>
      </form>
    </div>
    <div class= "contain">
      <h2>Friend List</h2>
      <div class= "flex">
        {% if friend %}
          {% for data in friend %}
            <div class= "flex-item">
              <div class= "friend">
                <div class= "friend-name">
                  {{ data.name }}
                </div>
                <a class= "friend-url" target="_new" href="{{ data.url }}">
                  {{ data.url }}
                </a>
                <div class= "friend-added-date">
                  {{ data.created_date }}
                </div>
              </div>
            </div>
          {% endfor %}
        {% else %}
        {% endif %}
      </div>
    </div>
  {% endblock %}

app_3/templates/app_3/form_result.html
{% extends "app_3/layout/base.html" %}
{% block title %} Pesan dari {{ name }} {% endblock %}
{% block content %}
<textarea readonly rows="5" class="form-control">&quot;{{message}}&quot;-{{name}} 
    by {{ email }}
</textarea>
{% endblock %}

{% block footer %}
    <p> &copy; {{name}} </p>
{% endblock %}

app_3/templates/app_3/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="App 3">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">    

    <title> 
        {% block title %} Friends of {{author}}{% endblock %}
    </title>
</head>
<style>
    body{
        background-color : orange;
    }
    .contain {
        margin-left: 15%;
        margin-right: 15%;
        padding-left: 2%;
        padding-right: 2%;
        background-color: white;
    }

    h2 {
        font-family: arial;
        text-align: center;
        margin-top: 8px;
        padding-top: 15px;
    }

    .friend-form {
        display: flex;
        flex-flow: column wrap;
        width: 100%;
        margin-left: auto;
        margin-right: auto;
        margin-bottom: 0;
        text-align: center;
        position: relative;
        background: white;
        border: 0 none;
        border-radius: 3px;
        padding: 20px 30px;
        box-sizing: border-box;
    }

    .name-form {
        text-align: center;
        border-style: inset;
        padding: 8px 0;
        border-radius: 5px;
        width: 100%;
    }

    .url-form {
        text-align: center;
        margin-top: 15px;
        border-radius: 5px;
        border-style: inset;
        padding: 10px 0;
        font: 13.3333px Arial;
        width: 100%;
    }

    .friend-button {
        font: 13.3333px Arial;
        padding: 10px, 0;
        margin-top: 15px;
        border-radius: 5px;
        padding: 5px 0;
        background-color: #3b5998;
        color: white;
    }

    .flex {
        width: 100%;
        margin-left: auto;
        margin-right: auto;
        padding: 20px 30px;
        box-sizing: border-box;
    }

    .flex-item {
        display: flex;
        flex-direction: row;
        padding: 10px 5px;
        border-radius: 5px;
    }

    .flex-item:hover {
        box-shadow: 1px 1px 0 0 rgba(0, 0, 0, 0.4);
        transition: all ease 0.5s;
        background-color: rgba(0, 0, 0, 0.03);
    }

    .friend {
        width: 100%;
        font: 13.3333px Arial;
    }

    .friend-name {
        float: left;
        width: 30%;
    }

    .friend-url {
        text-align: right;
        float: right;
        width: 55%;
        overflow: hidden;
    }

    .friend-added-date {
        text-align: right;
        clear: both;
        font-size: 13px;
    }


    @media screen and (max-width: 768px) {
        .contain {
            margin-left: 0;
            margin-right: 0;
        }

        .flex-item {
            box-shadow: 1px 1px 0 0 rgba(0, 0, 0, 0.4);
            background-color: rgba(0, 0, 0, 0.03);
        }

        .friend {
            overflow: visible;
        }

        .friend-name {
            float: none;
            width: 100%
        }

        .friend-url {
            float: none;
            text-align: left;
            width: 100%;
            font-size: 11px;
        }

        .friend-added-date {
            float: none;
        }

        .friend-button {
            padding: 3% 0;
        }

    }
</style>
<body>
    <header>
        {% include "app_3/partials/header.html" %}
    </header>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </div>

    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "app_3/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.js"></script> -->
</body>

 <!-- <script>
    $(function(){
      $('#form1').validate({
        rules: { //yang dicari name nya bukan id
          name:"required",
          age:{
            required: true,
            maxlength: 3
          }
        },
        messages:{
          name:"Jangan lupa diisi"
        },
        submitHandler: function(bebas){
          bebas.submit();
        }
      })
    })
</script>  -->
</html>

app_3/templates/app_3/partials/footer.html
<p style="margin: 10px;">&copy; {{author}}</p>

app_3/templates/app_3/partials/header.html
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'app-3:index' %}">Portofolio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
        
        </ul>
    </div><!--/.nav-collapse -->
    </div>
</nav>

app_3/templates/app_3/table.html
{% extends "app_3/layout/base.html" %}

{% block title %} Friends {% endblock %}

{% block content %}
<!--  Populate semua isi pesan dari model -->
<p>Add Friend</p>
<table class="table">
    
    <tbody>
        <!-- TODO, Kalau nama/email anon maka tr classnya jadi warning -->
        {% for i in friend %}
        <tr class="success">
            <td> {{i.name}} </td>
            <td> {{i.url}} </td>
            <td> {{i.created_date}} </td>
        </tr>             
        {% endfor %}
    </tbody>
</table>

{% endblock %}

percobaan/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ name }}</title>
</head>
<body>
    <h1>Hello my name is {{ name }}</h1>
    <article>I am {{ age }} years old</article>
</body>
</html>